#!/usr/bin/env bash
# Cloudflare Tunnel для ACP WebSocket bridge.
#
# Делает:
#   1. brew install cloudflare/cloudflare/cloudflared (если нет)
#   2. cloudflared tunnel login (интерактивно, один раз)
#   3. cloudflared tunnel create <name>
#   4. маршрутизирует <hostname> на tunnel
#   5. пишет ~/.cloudflared/config.yml c ingress → ws://127.0.0.1:<port>
#   6. sudo cloudflared service install (опц.) или просто print-runline
#
# Использование:
#   ./cloudflared-setup.sh acp.example.com            # дефолт name=acp-bridge port=8443
#   ./cloudflared-setup.sh acp.example.com my-tunnel  # кастомное имя тоннеля
#   ./cloudflared-setup.sh acp.example.com acp 9443   # кастомный порт bridge
#
set -euo pipefail

HOSTNAME="${1:-}"
TUNNEL_NAME="${2:-acp-bridge}"
BRIDGE_PORT="${3:-8443}"

if [ -z "$HOSTNAME" ]; then
    echo "Usage: $0 <hostname> [tunnel-name] [bridge-port]"
    echo "       $0 acp.example.com"
    echo "       $0 acp.example.com my-tunnel 9443"
    exit 1
fi

echo "=== Cloudflare Tunnel setup для ACP bridge ==="
echo "  hostname:    $HOSTNAME"
echo "  tunnel name: $TUNNEL_NAME"
echo "  bridge:      ws://127.0.0.1:$BRIDGE_PORT"
echo

# --- 1. cloudflared binary --------------------------------------------------

if ! command -v cloudflared >/dev/null 2>&1; then
    if ! command -v brew >/dev/null 2>&1; then
        echo "Homebrew не найден. Установи: https://brew.sh" >&2
        exit 1
    fi
    echo "→ устанавливаю cloudflared через brew…"
    brew install cloudflare/cloudflare/cloudflared
fi

echo "✓ cloudflared $(cloudflared --version | head -n1)"

# --- 2. cert.pem (tunnel login) ---------------------------------------------

CF_DIR="$HOME/.cloudflared"
mkdir -p "$CF_DIR"

if [ ! -f "$CF_DIR/cert.pem" ]; then
    echo "→ cloudflared tunnel login (откроется браузер, выбери домен для tunnel-ов)…"
    cloudflared tunnel login
fi

echo "✓ CF cert: $CF_DIR/cert.pem"

# --- 3. create tunnel (idempotent) ------------------------------------------

TUNNEL_ID="$(cloudflared tunnel list --output json 2>/dev/null | \
    /usr/bin/python3 -c "
import json, sys
name = sys.argv[1]
data = json.load(sys.stdin)
for t in data:
    if t.get('name') == name:
        print(t.get('id', ''))
        break
" "$TUNNEL_NAME" || true)"

if [ -z "$TUNNEL_ID" ]; then
    echo "→ создаю tunnel '$TUNNEL_NAME'…"
    cloudflared tunnel create "$TUNNEL_NAME"
    TUNNEL_ID="$(cloudflared tunnel list --output json | \
        /usr/bin/python3 -c "
import json, sys
name = sys.argv[1]
for t in json.load(sys.stdin):
    if t.get('name') == name:
        print(t.get('id', ''))
        break
" "$TUNNEL_NAME")"
else
    echo "✓ tunnel '$TUNNEL_NAME' уже существует"
fi

if [ -z "$TUNNEL_ID" ]; then
    echo "Не смог получить tunnel ID." >&2
    exit 1
fi

echo "✓ tunnel id: $TUNNEL_ID"

CREDS_FILE="$CF_DIR/$TUNNEL_ID.json"
if [ ! -f "$CREDS_FILE" ]; then
    echo "credentials-файл $CREDS_FILE не найден — возможно tunnel создан на другой машине." >&2
    echo "Перенеси json или пересоздай tunnel." >&2
    exit 1
fi

# --- 4. DNS route -----------------------------------------------------------

echo "→ привязываю $HOSTNAME к tunnel…"
# route dns идемпотентен — ругается если запись уже есть, игнорируем.
cloudflared tunnel route dns "$TUNNEL_NAME" "$HOSTNAME" 2>&1 | tee /tmp/cf-route.log || true

# --- 5. config.yml ----------------------------------------------------------

CONFIG_FILE="$CF_DIR/config.yml"
echo "→ пишу $CONFIG_FILE…"

cat > "$CONFIG_FILE" <<EOF
# Auto-generated by cloudflared-setup.sh
tunnel: $TUNNEL_ID
credentials-file: $CREDS_FILE

ingress:
  - hostname: $HOSTNAME
    service: ws://127.0.0.1:$BRIDGE_PORT
    originRequest:
      # Keep-alive: bridge шлёт ping каждые 30s; CF edge держит подольше.
      keepAliveTimeout: 60s
      # WS апгрейд требует http2Origin=false (default), оставляем.
      noTLSVerify: false
  - service: http_status:404
EOF

echo "✓ config готов"

# --- 6. Summary -------------------------------------------------------------

cat <<EOF

=== Готово ===

Ingress: https://$HOSTNAME → ws://127.0.0.1:$BRIDGE_PORT

Запуск tunnel (foreground):
  cloudflared tunnel run $TUNNEL_NAME

Запуск как launchd-сервис (фоном, автозапуск):
  sudo cloudflared service install
  sudo launchctl start com.cloudflare.cloudflared

Bridge (bez TLS, CF делает termination на edge):
  export ACP_WS_TOKEN=\$(openssl rand -hex 32)
  export ACP_WS_PORT=$BRIDGE_PORT
  export ACP_WS_BIND=127.0.0.1       # локально, трафик идёт через tunnel
  unset  ACP_WS_TLS_CERT ACP_WS_TLS_KEY
  # либо: export ACP_WS_NO_TLS=1 (если bridge требует явный флаг)
  npm run build && node dist/bridges/acp-websocket-bridge.js

В iOS Settings:
  URL:                     wss://$HOSTNAME/acp
  Bearer token:            \$ACP_WS_TOKEN
  Allow self-signed TLS:   OFF   (настоящий сертификат от CF)

ОПЦИОНАЛЬНО — закрыть tunnel за Zero Trust Access:
  1. Zero Trust → Access → Applications → Add application (Self-hosted)
     Application domain: $HOSTNAME
     Session duration: 24h
  2. Policies → Add: Allow if Emails include v.siresin@gmail.com
     (или Service Auth → Service Token, тогда iPhone в Settings вводит
      CF-Access-Client-Id / CF-Access-Client-Secret, остальные отбиваются 401)
  3. Zero Trust → Access → Service Tokens → Create:
     name: acp-ios → сохрани Client-Id + Client-Secret (secret показывается один раз!)

Проверка:
  curl -H "Authorization: Bearer \$ACP_WS_TOKEN" \\
       -H "CF-Access-Client-Id: <id>" \\
       -H "CF-Access-Client-Secret: <secret>" \\
       -H "Upgrade: websocket" -H "Connection: Upgrade" \\
       -H "Sec-WebSocket-Version: 13" \\
       -H "Sec-WebSocket-Key: \$(openssl rand -base64 16)" \\
       -v https://$HOSTNAME/acp
  → должен вернуть 101 Switching Protocols.
EOF
